/**
 *  Dummy action for compilation
 */
export const DUMMY = 'DUMMY';

/**
* Actions related to Toolbar
*/
export const INVENTORY_CLICK = 'INVENTORY_CLICK';
export const CHECKOUT_CLICK = 'CHECKOUT_CLICK';

/**
* Actions related to Log In and Authentication
*/
export const LOGIN_REQUEST_SENT = 'LOGIN_REQUEST_SENT';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
export const SIGNUP_REQUEST_SENT = 'SIGNUP_REQUEST_SENT';
export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS';
export const SIGNUP_REQUEST_FAILURE = 'SIGNUP_REQUEST_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

/**
* Actions related to basket and payment
*/
// export const BASKET_ADD_ITEM = 'BASKET_ADD_ITEM';
export const BASKET_DECREASE_COUNT = 'BASKET_DECREASE_COUNT';
export const BASKET_INCREASE_COUNT = 'BASKET_INCREASE_COUNT';
export const BASKET_REMOVE_ITEM = 'BASKET_REMOVE_ITEM';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const PAYMENT_COMPLETED = 'PAYMENT_COMPLETED';
export const TRANSACTION_REQUEST_SENT = 'TRANSACTION_REQUEST_SENT';
export const TRANSACTION_REQUEST_SUCCESS = 'TRANSACTION_REQUEST_SUCCESS';
export const TRANSACTION_REQUEST_FAILURE = 'TRANSACTION_REQUEST_FAILURE';
export const PAYMENT_METHOD_SELECTED = 'PAYMENT_METHOD_SELECTED';
export const CASH_RECEIVED = 'CASH_RECEIVED';
export const CHECKOUT_COMPLETED = 'CHECKOUT_COMPLETED';
export const RESET_PAYMENT = 'RESET_PAYMENT';

/**
* Actions related to UI
*/
// export const CHECKOUT = 'CHECKOUT';
// export const CHECKIN = 'CHECKIN';
export const TOGGLE_CHECKOUT = 'TOGGLE_CHECKOUT';

/**
* Product insertion
*/
export const SAVE_PRODUCT_REQUEST_SUCCESS = 'SAVE_PRODUCT_REQUEST_SUCCESS';
export const SAVE_PRODUCT_REQUEST_FAILURE = 'SAVE_PRODUCT_REQUEST_FAILURE';
export const SAVE_PRODUCT_REQUEST_SENT = 'SAVE_PRODUCT_REQUEST_SENT';

export const PRODUCT_C_REQUEST_SENT = 'PRODUCT_C_REQUEST_SENT';
export const PRODUCT_C_REQUEST_SUCCESS = 'PRODUCT_C_REQUEST_SUCCESS';
export const PRODUCT_C_REQUEST_FAILURE = 'PRODUCT_C_REQUEST_FAILURE';
export const PRODUCT_R_REQUEST_SENT = 'PRODUCT_R_REQUEST_SENT';
export const PRODUCT_R_REQUEST_SUCCESS = 'PRODUCT_R_REQUEST_SUCCESS';
export const PRODUCT_R_REQUEST_FAILURE = 'PRODUCT_R_REQUEST_FAILURE';
export const PRODUCT_U_REQUEST_SENT = 'PRODUCT_U_REQUEST_SENT';
export const PRODUCT_U_REQUEST_SUCCESS = 'PRODUCT_U_REQUEST_SUCCESS';
export const PRODUCT_U_REQUEST_FAILURE = 'PRODUCT_U_REQUEST_FAILURE';
export const PRODUCT_D_REQUEST_SENT = 'PRODUCT_D_REQUEST_SENT';
export const PRODUCT_D_REQUEST_SUCCESS = 'PRODUCT_D_REQUEST_SUCCESS';
export const PRODUCT_D_REQUEST_FAILURE = 'PRODUCT_D_REQUEST_FAILURE';


/**
* Actions for testing
*/
export const POPULATE_WITH_FAKE_DATA = 'POPULATE_WITH_FAKE_DATA';

/**
* category filter pane
*/
export const TOGGLE_CATEGORY = 'TOGGLE_CATEGORY';

/**
* business selector
*/
export const SELECT_BUSINESS = 'SELECT_BUSINESS';

/**
* business requests
*/
export const BUSINESS_C_REQUEST_SUCCESS = 'BUSINESS_C_REQUEST_SUCCESS';
export const BUSINESS_C_REQUEST_FAILURE = 'BUSINESS_C_REQUEST_FAILURE';
export const BUSINESS_C_REQUEST_SENT = 'BUSINESS_C_REQUEST_SENT';
export const BUSINESS_JOIN_REQUEST_SUCCESS = 'BUSINESS_JOIN_REQUEST_SUCCESS';
export const BUSINESS_JOIN_REQUEST_FAILURE = 'BUSINESS_JOIN_REQUEST_FAILURE';
export const BUSINESS_JOIN_REQUEST_SENT = 'BUSINESS_JOIN_REQUEST_SENT';
export const BUSINESS_CHECKIN_REQUEST_SUCCESFUL = 'BUSINESS_CHECKIN_REQUEST_SUCCESFUL';
export const BUSINESS_CHECKIN_REQUEST_FAILURE = 'BUSINESS_CHECKIN_REQUEST_FAILURE';
export const BUSINESS_CHECKIN_REQUEST_SENT = 'BUSINESS_CHECKIN_REQUEST_SENT';

/**
* notifications
*/
export const REQUESTS_REQUEST_SUCCESS = 'REQUESTS_REQUEST_SUCCESS';
export const REQUESTS_REQUEST_FAILURE = 'REQUESTS_REQUEST_FAILURE';
export const REQUESTS_REQUEST_SENT = 'REQUESTS_REQUEST_SENT';
export const ACCEPTANCE_REQUEST_SUCCESS = 'ACCEPTANCE_REQUEST_SUCCESS';
export const ACCEPTANCE_REQUEST_FAILURE = 'ACCEPTANCE_REQUEST_FAILURE';
export const ACCEPTANCE_REQUEST_SENT = 'ACCEPTANCE_REQUEST_SENT';

/*
*profile
*/
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const UPDATE_DETAILS_REQUEST_SUCCESS = 'UPDATE_DETAILS_REQUEST_SUCCESS';
export const UPDATE_DETAILS_REQUEST_FAILURE = 'UPDATE_DETAILS_REQUEST_FAILURE';
export const UPDATE_DETAILS_REQUEST_SENT = 'UPDATE_DETAILS_REQUEST_SENT';

export const DELETE_USER_REQUEST_SUCCESS = 'DELETE_USER_REQUEST_SUCCESS';
export const DELETE_USER_REQUEST_FAILURE = 'DELETE_USER_REQUEST_FAILURE';
export const DELETE_USER_REQUEST_SENT = 'DELETE_USER_REQUEST_SENT';

export const ROLE_REQUEST_SUCCESS = 'ROLE_REQUEST_SUCCESS';
export const ROLE_REQUEST_FAILURE = 'ROLE_REQUEST_FAILURE';
export const ROLE_REQUEST_SENT = 'ROLE_REQUEST_SENT';
